# The URL the site will be built for
base_url = "https://attoyss2023.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

external_links_target_blank = true

[extra]
# Put all your custom variables here
email = "attoyss2023@gmail.com"
start_date = "2023-09-13"
number_of_days = 3
timezone = "Europe/Vienna"
registration_form_iframe = "https://docs.google.com/forms/d/e/1FAIpQLSc6Lb_Hd1Y2tftnD3G72iKaT_39yOcRVfFqHowOZoMSdN0aGA/viewform?embedded=true"
registration_form_link = "https://forms.gle/abNs3Dfr6mCpS2nf8"
abstract_email = "attoyss2023+abstracts@gmail.com"