# On every push this script is executed
name: Build and deploy GH Pages

on:
 push:
  branches:
   - master
 pull_request:

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          version: 2022
          packages: >-
            auxhook
            bigintcalc
            bitset
            collection-fontsrecommended
            ec
            epstopdf-pkg
            etexcmds
            fontenc
            geometry
            gettitlestring
            graphics
            graphics-cfg
            graphicx
            hycolor
            hyperref
            iftex
            infwarerr
            inputenc
            intcalc
            kvdefinekeys
            kvoptions
            kvsetkeys
            l3backend
            latex
            latex-bin
            latexconfig
            latexmk
            letltxmacro
            mathptmx
            metafont
            mptopdf
            pdfescape
            pdftexcmds
            psnfss
            refcount
            rerunfilecheck
            uniquecounter
            url
      - name: Update APT
        run: sudo apt-get update
      - name: Install ImageMagick and Ghostscript
        run: sudo apt-get install imagemagick ghostscript
      - name: Change ImageMagick policy to allow pdf->png conversion.
        # https://wessman.co/github-actions-imagemagick
        run: |
          sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
      - name: Generate abstract thumbnails
        run: |
          if test -d "content/programme/talks"; then
            cd content/programme/talks && ./make-previews.sh
          fi
      - name: Build abstract templates
        run: cd abstract-templates/LaTeX && make
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_ONLY: ${{ github.ref != 'refs/heads/master' }}
          BUILD_FLAGS: "${{ github.ref != 'refs/heads/master' && '--drafts' || ''}}"
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
