# On every push this script is executed
name: Build and deploy GH Pages

on:
 push:
  branches:
   - master
 pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout master
        uses: actions/checkout@v3.0.0
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: >-
            graphicx
            inputenc
            fontenc
            mathptmx
            hyperref
            geometry
            latexmk
      - name: Build abstract templates
        run: cd abstract-templates/LaTeX && make
      - name: Build only
        uses: shalzz/zola-deploy-action@v0.16.1-1
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          # A GitHub token is not necessary when BUILD_ONLY is true
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout master
        uses: actions/checkout@v3.0.0
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.16.1-1
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
